# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

stages:
- build
- test
- release
- deploy

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .


release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push     $CI_REGISTRY_IMAGE